name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: rustup install nightly && rustup default nightly && cargo test
        #-  name: Clippy check
        # env:
        #   DATABASE_URL: postgres://monitoring_ci_user:monitoring_ci_password@postgres:5432/monitoring
        #run: rustup component add clippy && cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --release
      - name: Publish docker image to Github Packages
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/nikitavbv/cloud-storage-proxy/cloud-storage-proxy
          registry: docker.pkg.github.com
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish docker image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nikitavbv/cloud-storage-proxy
          registry: docker.io
          username: nikitavbv
          password: ${{ secrets.docker_hub_token }}
          tags: "latest,0.1.1"